import type { Metadata } from "next";
import { ADLaM_Display, AR_One_Sans, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
// If loading a variable font, you don't need to specify the font weight
const inter = AR_One_Sans({
  subsets: ['latin'],weight:'600'
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
